<?php
session_start();
header('Content-Type: application/json; charset=utf-8');
function out($a,$c=200){http_response_code($c);echo json_encode($a,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function db(){ $p=__DIR__.'/xls/grades.sqlite'; if(!is_dir(dirname($p))) mkdir(dirname($p),0775,true); $pdo=new PDO('sqlite:'.$p); $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION); $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC); init($pdo); return $pdo; }
function col($pdo,$t,$c){foreach($pdo->query("PRAGMA table_info($t)")->fetchAll() as $r){if($r['name']===$c)return true;}return false;}
function sha($p){return 'sha256$'.hash('sha256',$p);} 
function vpass($p,$h){return str_starts_with($h,'sha256$')?hash_equals($h,sha($p)):password_verify($p,$h);} 
function init($pdo){
$pdo->exec('PRAGMA foreign_keys=ON');
$pdo->exec("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT NOT NULL UNIQUE,display_name TEXT,password_hash TEXT,role TEXT NOT NULL DEFAULT 'teacher',is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)");
foreach([['password_hash','TEXT'],['is_active','INTEGER NOT NULL DEFAULT 1']] as $x){if(!col($pdo,'users',$x[0]))$pdo->exec("ALTER TABLE users ADD COLUMN {$x[0]} {$x[1]}");}
$pdo->exec("CREATE TABLE IF NOT EXISTS subjects(id INTEGER PRIMARY KEY AUTOINCREMENT,teacher_id INTEGER NOT NULL,slug TEXT NOT NULL UNIQUE,full_name TEXT,source_filename TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(teacher_id) REFERENCES users(id) ON DELETE CASCADE)");
$pdo->exec("CREATE TABLE IF NOT EXISTS students(id INTEGER PRIMARY KEY AUTOINCREMENT,student_key TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)");
$pdo->exec("CREATE TABLE IF NOT EXISTS grades(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,subject_id INTEGER NOT NULL,I REAL,II REAL,III REAL,F REAL,O REAL,E REAL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(student_id,subject_id),FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE)");
$pdo->exec("CREATE TABLE IF NOT EXISTS teaching_memory(id INTEGER PRIMARY KEY AUTOINCREMENT,subject_id INTEGER NOT NULL UNIQUE,cycle TEXT,professional_module TEXT,academic_year TEXT,responsible_teacher TEXT,programming_units TEXT,planned_timing TEXT,actual_timing TEXT,timing_modifications TEXT,developed_activities TEXT,used_resources TEXT,first_evaluation TEXT,second_evaluation TEXT,third_evaluation TEXT,ordinary_evaluation TEXT,extraordinary_evaluation TEXT,detected_difficulties TEXT,relevant_incidents TEXT,diversity_measures TEXT,teaching_practice_assessment TEXT,improvement_proposals TEXT,complementary_activities TEXT,closing_text TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE)");
$n=(int)$pdo->query('SELECT COUNT(*) n FROM users')->fetch()['n']; if($n===0){$st=$pdo->prepare("INSERT INTO users(username,display_name,password_hash,role,is_active) VALUES('jocarsa','Jocarsa',?,'admin',1)");$st->execute([password_hash('jocarsa',PASSWORD_DEFAULT)]);} }
function body(){return json_decode(file_get_contents('php://input')?:'{}',true)?:[];} 
function me($pdo){if(empty($_SESSION['uid']))return null;$s=$pdo->prepare('SELECT id,username,display_name,role,is_active FROM users WHERE id=? AND is_active=1');$s->execute([$_SESSION['uid']]);return $s->fetch()?:null;} 
function need($pdo){$u=me($pdo); if(!$u)out(['ok'=>false,'error'=>'No autenticado'],401); return $u;} function admin($pdo){$u=need($pdo); if($u['role']!=='admin')out(['ok'=>false,'error'=>'Administrador requerido'],403); return $u;}
function subj($pdo,$id){$u=need($pdo);$s=$pdo->prepare('SELECT s.*,COALESCE(NULLIF(s.full_name,""),s.slug) full_name,u.username teacher_username,u.display_name teacher_display_name FROM subjects s JOIN users u ON u.id=s.teacher_id WHERE s.id=?');$s->execute([$id]);$r=$s->fetch(); if(!$r)out(['ok'=>false,'error'=>'Asignatura no encontrada'],404); if($u['role']!=='admin'&&(int)$r['teacher_id']!==(int)$u['id'])out(['ok'=>false,'error'=>'Sin permiso'],403); return $r;}
$pdo=db(); $a=$_GET['action']??'auth_status';
try{
if($a==='auth_status')out(['ok'=>true,'authenticated'=>(bool)me($pdo),'user'=>me($pdo)]);
if($a==='login'){ $b=body();$s=$pdo->prepare('SELECT * FROM users WHERE username=? AND is_active=1');$s->execute([trim($b['username']??'')]);$u=$s->fetch(); if(!$u||!vpass($b['password']??'',(string)$u['password_hash']))out(['ok'=>false,'error'=>'Credenciales incorrectas'],401); $_SESSION['uid']=(int)$u['id']; out(['ok'=>true,'user'=>['id'=>$u['id'],'username'=>$u['username'],'display_name'=>$u['display_name'],'role'=>$u['role']]]);}
if($a==='logout'){session_destroy();out(['ok'=>true]);}
if($a==='users'){admin($pdo);$r=$pdo->query('SELECT u.id,u.username,u.display_name,u.role,u.is_active,COUNT(s.id) total_subjects FROM users u LEFT JOIN subjects s ON s.teacher_id=u.id GROUP BY u.id ORDER BY u.username')->fetchAll();out(['ok'=>true,'users'=>$r]);}
if($a==='user_save'){admin($pdo);$b=body();$id=(int)($b['id']??0);$p=$b['password']??''; if(trim($b['username']??'')==='')out(['ok'=>false,'error'=>'Usuario obligatorio'],400); if($id){if($p!==''){$s=$pdo->prepare('UPDATE users SET username=?,display_name=?,role=?,is_active=?,password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([$b['username'],$b['display_name']??'',$b['role']??'teacher',!empty($b['is_active'])?1:0,password_hash($p,PASSWORD_DEFAULT),$id]);}else{$s=$pdo->prepare('UPDATE users SET username=?,display_name=?,role=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([$b['username'],$b['display_name']??'',$b['role']??'teacher',!empty($b['is_active'])?1:0,$id]);}}else{if($p==='')out(['ok'=>false,'error'=>'Contraseña obligatoria'],400);$s=$pdo->prepare('INSERT INTO users(username,display_name,role,is_active,password_hash) VALUES(?,?,?,?,?)');$s->execute([$b['username'],$b['display_name']??'',$b['role']??'teacher',!empty($b['is_active'])?1:0,password_hash($p,PASSWORD_DEFAULT)]);} out(['ok'=>true]);}
if($a==='user_delete'){ $u=admin($pdo);$id=(int)(body()['id']??0); if($id===(int)$u['id'])out(['ok'=>false,'error'=>'No puedes eliminarte'],400);$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);out(['ok'=>true]);}
if($a==='subjects'){ $u=need($pdo); if($u['role']==='admin'){$s=$pdo->query('SELECT s.id,s.slug,COALESCE(NULLIF(s.full_name,""),s.slug) full_name,s.source_filename,s.teacher_id,u.username teacher_username,u.display_name teacher_display_name,COUNT(g.id) total_grades,CASE WHEN tm.id IS NULL THEN 0 ELSE 1 END has_memory FROM subjects s JOIN users u ON u.id=s.teacher_id LEFT JOIN grades g ON g.subject_id=s.id LEFT JOIN teaching_memory tm ON tm.subject_id=s.id GROUP BY s.id ORDER BY full_name');}else{$s=$pdo->prepare('SELECT s.id,s.slug,COALESCE(NULLIF(s.full_name,""),s.slug) full_name,s.source_filename,s.teacher_id,u.username teacher_username,u.display_name teacher_display_name,COUNT(g.id) total_grades,CASE WHEN tm.id IS NULL THEN 0 ELSE 1 END has_memory FROM subjects s JOIN users u ON u.id=s.teacher_id LEFT JOIN grades g ON g.subject_id=s.id LEFT JOIN teaching_memory tm ON tm.subject_id=s.id WHERE s.teacher_id=? GROUP BY s.id ORDER BY full_name');$s->execute([$u['id']]);} out(['ok'=>true,'subjects'=>$s->fetchAll()]);}
if($a==='grades'){ $id=(int)($_GET['subject_id']??0);$su=subj($pdo,$id);$s=$pdo->prepare('SELECT st.id student_id,st.full_name,g.I,g.II,g.III,g.F,g.O,g.E FROM grades g JOIN students st ON st.id=g.student_id WHERE g.subject_id=? ORDER BY st.full_name');$s->execute([$id]);out(['ok'=>true,'subject'=>$su,'rows'=>$s->fetchAll()]);}
if($a==='stats'){ $id=(int)($_GET['subject_id']??0);$su=subj($pdo,$id);$res=[];foreach(['I','II','III','F','O','E'] as $ev){$s=$pdo->prepare("SELECT COUNT($ev) total,SUM(CASE WHEN $ev>=5 THEN 1 ELSE 0 END) passed,SUM(CASE WHEN $ev<5 AND $ev IS NOT NULL THEN 1 ELSE 0 END) failed,AVG($ev) average FROM grades WHERE subject_id=? AND $ev IS NOT NULL");$s->execute([$id]);$r=$s->fetch();$t=(int)$r['total'];$p=(int)$r['passed'];$f=(int)$r['failed'];$res[$ev]=['total'=>$t,'passed'=>$p,'failed'=>$f,'pass_pct'=>$t?round($p/$t*100,2):0,'fail_pct'=>$t?round($f/$t*100,2):0,'average'=>$r['average']!==null?round((float)$r['average'],2):null];}out(['ok'=>true,'subject'=>$su,'stats'=>$res]);}
if($a==='memory_get'){ $id=(int)($_GET['subject_id']??0);$su=subj($pdo,$id);$s=$pdo->prepare('SELECT * FROM teaching_memory WHERE subject_id=?');$s->execute([$id]);$m=$s->fetch(); if(!$m)$m=['subject_id'=>$id,'professional_module'=>$su['full_name'],'responsible_teacher'=>$su['teacher_display_name']?:$su['teacher_username'],'closing_text'=>'Quedo a vuestra disposición para cualquier aclaración.']; out(['ok'=>true,'subject'=>$su,'memory'=>$m]);}
if($a==='memory_save'){ $b=body();$id=(int)($b['subject_id']??0);subj($pdo,$id);$fields=['cycle','professional_module','academic_year','responsible_teacher','programming_units','planned_timing','actual_timing','timing_modifications','developed_activities','used_resources','first_evaluation','second_evaluation','third_evaluation','ordinary_evaluation','extraordinary_evaluation','detected_difficulties','relevant_incidents','diversity_measures','teaching_practice_assessment','improvement_proposals','complementary_activities','closing_text'];$cols='subject_id,'.implode(',',$fields);$ph='?'.str_repeat(',?',count($fields));$upd=implode(',',array_map(fn($f)=>"$f=excluded.$f",$fields)).',updated_at=CURRENT_TIMESTAMP';$vals=[$id];foreach($fields as $f)$vals[]=trim((string)($b[$f]??''));$pdo->prepare("INSERT INTO teaching_memory($cols) VALUES($ph) ON CONFLICT(subject_id) DO UPDATE SET $upd")->execute($vals);out(['ok'=>true]);}
out(['ok'=>false,'error'=>'Acción no válida'],400);
}catch(Throwable $e){out(['ok'=>false,'error'=>$e->getMessage()],500);} 
